LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\BALANCE_20211022.pipe'
TRUNCATE
INTO TABLE BALANCE
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
ACTION_TYPE,
RECORD_SEQ,
MEMBER_ID,
AWARD_MILES,
QUALIFYING_MILES,
QUALIFYING_SECTORS
)