LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\DE_MERGE_POINTERS_20211022.pipe'
TRUNCATE
INTO TABLE DE_MERGE_POINTERS
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
ACTION_TYPE,
RECORD_SEQ,
MERGE_ISN,
MERGED_ACCOUNT_ID,
ACTIVE_ACCOUNT_ID,
OPERATION_DATE
)
