LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_ACCRUAL_EXPIRY_MAP_20211022.pipe'
TRUNCATE
INTO TABLE LP_ACCRUAL_EXPIRY_MAP
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NR,
RECOD_SEQ,
TRANSACTION_REFERENCE,
EXPIRY_DATE,
REVERSED,
BASE_UNITS,
BONUS_UNITS_
)
