LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_ATTACHMENTS_20211022.pipe'
TRUNCATE
INTO TABLE LP_ATTACHMENTS
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NUMBER,
NOTE_INDEX,
FILENAME,
UNIQUE_FILENAME,
PATH,
LAST_UPDATE_BY,
LAST_UPDATE_ON
)
