LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_COMMUNICATION_20211022.pipe'
TRUNCATE
INTO TABLE LP_COMMUNICATION
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NUMBER,
NOTE_INDEX,
OPEN_DATE,
CLOSE_DATE,
STATUS,
ORIGIN,
MAIN_CATEGORY,
SUB_CATEGORY,
SHORT_DESCRIPTION,
NOTE,
PRIORITY,
ATTACHMENT_AVAILABLE,
MESSAGE_TYPE,
LAST_UPDATE_BY,
LAST_UPDATE_ON
)