LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_EXPIRY_EXTEND_REINSTATE_20211022.pipe'
TRUNCATE
INTO TABLE LP_EXPIRY_EXTEND_REINSTATE
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NR,
RECOD_SEQ,
OLD_EXP_DATE,
NEW_EXPIRY_DATE,
MILES_EXTENDED,
EXTENTION_TYPE,
TRANSACTION_REFERENCE,
PAYMENT_REFERENCE,
LAST_UPDATE_BY,
LAST_UPDATE_ON
)