LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_FAMILY_POOL_LOG_20211022.pipe'
TRUNCATE
INTO TABLE LP_FAMILY_POOL_LOG
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NUMBER_HEAD,
MEMBERSHIP_NUMBER_MEMBER,
SEQUENCE,
ACTION,
LOG_ENTRY,
POOL_STATUS,
LAST_UPDATE_BY,
LAST_UPDATE_ON
)