LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_FAMILY_POOL_DETAILS_20211022.pipe'
TRUNCATE
INTO TABLE LP_FAMILY_POOL_DETAILS
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NUMBER_HEAD,
MEMBERSHIP_NUMBER_MEMBER,
BEGIN_DATE,
END_DATE,
RECORD_STATUS,
RELATIONSHIP,
LINK_STATUS,
LINK_REQUEST,
LAST_UPDATE_BY,
LAST_UPDATE_ON
)