LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_MEMBER_EXPIRY_20211022.pipe'
TRUNCATE
INTO TABLE LP_MEMBER_EXPIRY
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NUMBER,
EXPIRY_DATE,
EXPIRED_MILES,
STATEMENT_DATE,
LAST_UPDATE_BY,
LAST_UPDATE_ON
)