LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_MEMBER_VERIFICATIONS_20211022.pipe'
TRUNCATE
INTO TABLE LP_MEMBER_VERIFICATIONS
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NUMBER,
VERIFICATION_TYPE,
VERIFICATION_STATUS,
EXPIRY_DATE,
VALIDATE_KEY,
SEQUENCE,
LAST_UPDATE_BY,
LAST_UPDATE_ON
)