LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_REDEMPTION_EXPIRY_MAP_20211022.pipe'
TRUNCATE
INTO TABLE LP_REDEMPTION_EXPIRY_MAP
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NR,
RECOD_SEQ,
TRANSACTION_REFERENCE,
EXPIRY_DATE,
USED_UNITS
)