LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\LP_STATEMENT_FUTURE_EXPIRY_20211022.pipe'
TRUNCATE
INTO TABLE LP_STATEMENT_FUTURE_EXPIRY
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NUMBER,
STATEMENT_DATE,
EXPIRY_DATE,
UNITS_TO_EXPIRY
)