LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\MEMBER_AWD_USERS_20211022.pipe'
TRUNCATE
INTO TABLE MEMBER_AWD_USERS
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
ACTION_TYPE,
RECORD_SEQ,
MEMBER_AWD_USERS_SEQ,
MEMBER_AWD_ID,
NAME,
SURNAME,
BIRTH_DATE,
SOCIAL_SECURITY_NUMBER,
INSERTED_BY,
INSERT_DATE,
AMENDED_BY,
AMEND_DATE
)