LOAD DATA
CHARACTERSET UTF8
INFILE 'F:\AIC\RELATIONSHIP_MASTER_20211022.pipe'
TRUNCATE
INTO TABLE RELATIONSHIP_MASTER
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
ACTION_TYPE,
RECORD_SEQ,
ISN,
RELATIONSHIP_TYPE_ISN,
HEAD_MEMBER_ID,
INSERT_DATE,
INSERTED_BY,
AMEND_DATE,
AMENDED_BY,
STATUS
)