LOAD DATA
CHARACTERSET UTF8
INFILE '..\..\MIGRATION_DATA\De_Merge_Pointers.csv'
TRUNCATE
INTO TABLE DE_MERGE_POINTERS
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
ACTION_TYPE,
RECORD_SEQ,
MERGE_ISN,
MERGED_ACCOUNT_ID,
ACTIVE_ACCOUNT_ID,
OPERATION_DATE
)
