LOAD DATA
CHARACTERSET UTF8
INFILE '..\..\MIGRATION_DATA\LP_ACCRUAL_EXPIRY_MAP.csv'
TRUNCATE
INTO TABLE LP_ACCRUAL_EXPIRY_MAP
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NR,
RECOD_SEQ,
TRANSACTION_REFERENCE,
EXPIRY_DATE,
REVERSED,
BASE_UNITS,
BONUS_UNITS_
)
