LOAD DATA
CHARACTERSET UTF8
INFILE '..\..\MIGRATION_DATA\LP_FAMILY_POOL_HEAD.csv'
TRUNCATE
INTO TABLE LP_FAMILY_POOL_HEAD
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NUMBER_HEAD,
BEGIN_DATE,
END_DATE,
ACTIVATION_DATE,
POOL_STATUS,
POOL_SPLIT_HEAD,
POOL_SPLIT_MEMBER,
LAST_UPDATE_BY,
LAST_UPDATE_ON
)