LOAD DATA
CHARACTERSET UTF8
INFILE '..\..\MIGRATION_DATA\LP_FAMILY_POOL_DETAILS.csv'
TRUNCATE
INTO TABLE LP_FAMILY_POOL_DETAILS
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NUMBER_HEAD,
MEMBERSHIP_NUMBER_MEMBER,
BEGIN_DATE,
END_DATE,
RECORD_STATUS,
RELATIONSHIP,
LINK_STATUS,
LINK_REQUEST,
LAST_UPDATE_BY,
LAST_UPDATE_ON
)