LOAD DATA
CHARACTERSET UTF8
INFILE '..\..\MIGRATION_DATA\LP_REDEMPTION_EXPIRY_MAP.csv'
TRUNCATE
INTO TABLE LP_REDEMPTION_EXPIRY_MAP
FIELDS TERMINATED BY "|"
TRAILING NULLCOLS
(
RECORD_SEQ,
MEMBERSHIP_NR,
RECOD_SEQ,
TRANSACTION_REFERENCE,
EXPIRY_DATE,
USED_UNITS
)